"""initial schema

Revision ID: 730a59f9d341
Revises: 
Create Date: 2026-10-07 18:30:15.771634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '730a59f9d341'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_key', sa.String(length=64), nullable=False),
    sa.Column('analysis', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job')),
    sa.UniqueConstraint('request_key', name=op.f('uq_job_request_key'))
    )
    op.create_table('protein',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seq_sha256', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_protein')),
    sa.UniqueConstraint('seq_sha256', name=op.f('uq_protein_seq_sha256'))
    )
    op.create_table('structure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protein_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_version', sa.String(length=16), nullable=False),
    sa.Column('gcs_uri', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['protein_id'], ['protein.id'], name=op.f('fk_structure_protein_id_protein')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_structure')),
    sa.UniqueConstraint('protein_id', 'source', 'source_version', name=op.f('uq_structure_protein_id_source_source_version'))
    )
    op.create_table('analysis_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('structure_id', sa.Integer(), nullable=False),
    sa.Column('tool', sa.String(length=32), nullable=False),
    sa.Column('tool_version', sa.String(length=64), nullable=False),
    sa.Column('params_hash', sa.String(length=64), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', name='status', native_enum=False, length=16), server_default='pending', nullable=False),
    sa.Column('output_gcs_uri', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'running', 'succeeded', 'failed')", name=op.f('ck_analysis_run_status')),
    sa.ForeignKeyConstraint(['structure_id'], ['structure.id'], name=op.f('fk_analysis_run_structure_id_structure')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_run')),
    sa.UniqueConstraint('structure_id', 'tool', 'tool_version', 'params_hash', name=op.f('uq_analysis_run_structure_id_tool_tool_version_params_hash'))
    )
    op.create_table('job_protein',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('accession', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', name='status', native_enum=False, length=16), server_default='pending', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('protein_id', sa.Integer(), nullable=True),
    sa.Column('analysis_run_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'running', 'succeeded', 'failed')", name=op.f('ck_job_protein_status')),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_run.id'], name=op.f('fk_job_protein_analysis_run_id_analysis_run')),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('fk_job_protein_job_id_job')),
    sa.ForeignKeyConstraint(['protein_id'], ['protein.id'], name=op.f('fk_job_protein_protein_id_protein')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_protein')),
    sa.UniqueConstraint('job_id', 'accession', name=op.f('uq_job_protein_job_id_accession'))
    )
    op.create_table('pocket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('volume_a3', sa.Float(), nullable=False),
    sa.Column('mean_sasa_a2', sa.Float(), nullable=True),
    sa.Column('mean_plddt', sa.Float(), nullable=True),
    sa.Column('residues', postgresql.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_run.id'], name=op.f('fk_pocket_analysis_run_id_analysis_run')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pocket')),
    sa.UniqueConstraint('analysis_run_id', 'rank', name=op.f('uq_pocket_analysis_run_id_rank'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pocket')
    op.drop_table('job_protein')
    op.drop_table('analysis_run')
    op.drop_table('structure')
    op.drop_table('protein')
    op.drop_table('job')
    # ### end Alembic commands ###
